validate

diff --git a/root/etc/init.d/change-mac b/root/etc/init.d/change-mac
--- a/root/etc/init.d/change-mac
+++ b/root/etc/init.d/change-mac
@@ -17,12 +17,23 @@ CONFIG_NAME="change-mac"
 TYPEDSECTION="change-mac"
 
 
-change_mac() {
-	local ucivv="interface random_mode mac_type mac_type_specific mac_type_vendor"
+validate_section() {
+	uci_load_validate $CONFIG_NAME $TYPEDSECTION "$1" "$2" \
+		'interface:list(network)' \
+		'random_mode:or("disorderly", "sequence"):disorderly' \
+		'mac_type:or("locally", "specific", "vendor"):locally' \
+		'mac_type_specific:string' \
+		'mac_type_vendor:string'
+}
 
-	for _var in $ucivv; do
-		eval "local $_var=\$(config_get $1 $_var 2>/dev/null)"
-	done
+change_mac() {
+#	local ucivv="interface random_mode mac_type mac_type_specific mac_type_vendor"
+#
+#	for _var in $ucivv; do
+#		eval "local $_var=\$(config_get $1 $_var 2>/dev/null)"
+#	done
+
+	[ "$2" == "0" ] || { >&2 echo "section $1 validation failed"; return 1; }
 
 #	for _var in $ucivv; do
 #		eval "echo \"$_var=\$$_var\""
@@ -51,7 +62,9 @@ procd_close_instance
 
 restore_mac() {
 
-	local interface=$(config_get $1 interface 2>/dev/null)
+#	local interface=$(config_get $1 interface 2>/dev/null)
+
+	[ "$2" == "0" ] || { >&2 echo "section $1 validation failed"; return 1; }
 
 procd_open_instance
 procd_set_param command "$PROG" $interface
@@ -69,7 +82,7 @@ start_service() {
 	eval "enabled=\$CONFIG_${CONFIG_SECTIONS%% *}_enabled"
 	[ "${enabled:-0}" -gt "0" -o -n "$action" ] || return 1
 
-	config_foreach "${action:=change_mac}" "$TYPEDSECTION"
+	config_foreach validate_section "$TYPEDSECTION" "${action:=change_mac}"
 }
 
 stop_service() {
